Repository paketo-buildpacks/libpak, pull requests merged in 2021-11, with the labels that each got.

#97 Fixes issues with incorrect indentation
  bard/writer.go
  bard/writer_test.go
Labels: type:bug, semver:patch

#104 Adds convenience methods for using the Syft CLI to create SBoM information
  buildpack.go
  go.mod
  go.sum
  layer.go
  sherpa/init_test.go
  sherpa/mocks/sbom_scanner.go
  sherpa/sbom.go
  sherpa/sbom_test.go
Labels: type:enhancement, semver:minor

#106 Adds mock that was missing and not checked in
  sbom/mocks/sbom_scanner.go
Labels: type:bug, semver:patch

#107 Use build-specific settings for effect across windows and unix
  effect/executor.go
  effect/executor_unix.go
  effect/executor_windows.go
Labels: type:bug, semver:patch

#109 Fix build flag for non windows files
  effect/executor_unix.go
Labels: type:bug, semver:patch

#110 Bump to libcnb 1.25.1
  go.mod
  go.sum
  layer_test.go
Labels: type:dependency-upgrade, semver:patch
