Repository paketo-buildpacks/libpak, pull requests merged in 2021-09, with the labels that each got.

#82 Support wildcard stacks in DependencyResolver
  buildpack.go
  buildpack_test.go
Labels: type:enhancement, semver:patch

#83 Skip `.git` folders in file listings
  sherpa/file_listing.go
  sherpa/file_listing_test.go
Labels: type:enhancement, semver:minor

#81 Add Logging of Bindings Information for better UX
  bindings/resolve.go
  bindings/resolve_test.go
Labels: type:enhancement, semver:patch

#85 Revert "Add Logging of Bindings Information for better UX"
  bindings/resolve.go
  bindings/resolve_test.go
Labels: type:task, semver:patch

#31 Helper Helpers
  buildpack.go
  buildpack_test.go
  sherpa/env_var.go
  sherpa/env_var_test.go
  sherpa/init_test.go
Labels: type:enhancement, semver:minor

#88 Do not assume buildpack id ends with `-buildpacks`
  carton/package_dependency.go
  carton/package_dependency_test.go
Labels: type:enhancement, semver:patch
