Repository paketo-buildpacks/libpak, pull requests merged in 2021-12, with the labels that each got.

#112 Add flags to update cpe & purl
  carton/buildpack_dependency.go
  carton/buildpack_dependency_test.go
  cmd/update-buildpack-dependency/main.go
Labels: type:enhancement, semver:minor

#114 Fixes a bug where buildpack_dependency's `Update(..)` method will update the wrong dependencies
  carton/buildpack_dependency.go
  carton/buildpack_dependency_test.go
Labels: type:bug, semver:patch

#115 Remove unnecessary coversion from XML > JSON for CycloneDx + syft
  go.mod
  go.sum
  sbom/sbom.go
  sbom/sbom_test.go
Labels: type:enhancement, semver:patch
