Repository paketo-buildpacks/libpak, pull requests merged in 2023-09, with the labels that each got.

#284 libpak API evolution
  build.go
  build_test.go
  buildmodule.go
  buildmodule_test.go
  carton/build_image_dependency.go
  carton/buildmodule_dependency.go
  carton/lifecycle_dependency.go
  carton/package.go
  carton/package_dependency.go
  dependency_cache.go
  dependency_cache_test.go
  detect.go
  detect_test.go
  generate.go
  generate_test.go
  internal/environment_writer.go
  internal/environment_writer_test.go
  internal/exit_handler.go
  internal/exit_handler_test.go
  internal/toml_writer.go
  internal/toml_writer_test.go
  layer.go
  layer_test.go
  log/formatter.go
  log/formatter_test.go
  log/init_test.go
  log/logger.go
  log/logger_test.go
  log/writer.go
  log/writer_test.go
  sbom/sbom.go
  sbom/sbom_test.go
Labels: type:enhancement, semver:major

#273 adds logic to remove http query params from destination file name
  dependency_cache.go
  dependency_cache_test.go
Labels: type:bug, semver:patch

#196 Add Source and Source256 fields to dependencies in buildpack.toml.
  carton/buildpack_dependency.go
  carton/buildpack_dependency_test.go
  carton/package_dependency_test.go
  carton/package_test.go
  cmd/update-buildpack-dependency/main.go
Labels: type:enhancement, semver:minor
