Repository paketo-buildpacks/libpak, pull requests merged in 2024-10, with the labels that each got.

#366 Add skip-path Feature for Dependency Mirrors
  dependency_cache.go
  dependency_cache_test.go
Labels: type:enhancement, semver:minor

#371 Fix lints
  build_test.go
  buildmodule.go
  buildmodule_test.go
  buildpack_plan_test.go
  carton/build_image_dependency.go
  carton/build_image_dependency_test.go
  carton/buildmodule_dependency.go
  carton/buildmodule_dependency_test.go
  carton/lifecycle_dependency.go
  carton/lifecycle_dependency_test.go
  carton/netrc.go
  carton/netrc_test.go
  carton/package_dependency.go
  carton/package_dependency_test.go
  carton/package_test.go
  crush/crush.go
  crush/crush_test.go
  dependency_cache.go
  dependency_cache_test.go
  detect_test.go
  effect/executor.go
  effect/executor_unix.go
  formatter_test.go
  generate_test.go
  golangci.yaml
  internal/entry_writer_test.go
  internal/environment_writer.go
  internal/exit_handler_test.go
  internal/toml_marshal_test.go
  internal/toml_writer.go
  internal/toml_writer_test.go
  layer_test.go
  log/formatter_test.go
  log/logger.go
  log/logger_test.go
  log/writer_test.go
  main.go
  main_test.go
  sbom/sbom.go
  sbom/sbom_test.go
  sherpa/copy_dir_test.go
  sherpa/copy_file_test.go
  sherpa/env_var_test.go
  sherpa/exists.go
  sherpa/exists_test.go
  sherpa/file_listing_test.go
  sherpa/nodejs_test.go
  sherpa/sherpa_test.go
  stack_test.go
Labels: semver:major, type:task

#369 Bump Go modules & pipeline
  .github/pipeline-version
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
  Makefile
  build_test.go
  buildmodule.go
  buildmodule_test.go
  buildpack_plan_test.go
  carton/build_image_dependency.go
  carton/build_image_dependency_test.go
  carton/buildmodule_dependency.go
  carton/buildmodule_dependency_test.go
  carton/lifecycle_dependency.go
  carton/lifecycle_dependency_test.go
  carton/netrc.go
  carton/netrc_test.go
  carton/package_dependency.go
  carton/package_dependency_test.go
  carton/package_test.go
  crush/crush.go
  crush/crush_test.go
  dependency_cache.go
  dependency_cache_test.go
  detect_test.go
  effect/executor.go
  effect/executor_unix.go
  formatter_test.go
  generate_test.go
  go.mod
  go.sum
  golangci.yaml
  internal/entry_writer_test.go
  internal/environment_writer.go
  internal/exit_handler_test.go
  internal/toml_marshal_test.go
  internal/toml_writer.go
  internal/toml_writer_test.go
  layer_test.go
  log/formatter_test.go
  log/logger.go
  log/logger_test.go
  log/writer_test.go
  main.go
  main_test.go
  sbom/sbom.go
  sbom/sbom_test.go
  sherpa/copy_dir_test.go
  sherpa/copy_file.go
  sherpa/copy_file_test.go
  sherpa/env_var_test.go
  sherpa/exists.go
  sherpa/exists_test.go
  sherpa/file_listing_test.go
  sherpa/nodejs_test.go
  sherpa/sherpa_test.go
  stack_test.go
  tools/go.mod
  tools/go.sum
Labels: type:dependency-upgrade, semver:patch

#372 Update stacks
  stack.go
  stack_test.go
Labels: type:enhancement, semver:major
