Repository paketo-buildpacks/libpak, pull requests merged in 2024-07, with the labels that each got.

#352 Change `syft packages` to `syft scan`
  sbom/sbom.go
Labels: type:bug, semver:patch

#351 Change `syft packages` to `syft scan`
  sbom/sbom.go
Labels: type:bug, semver:patch

#345 Automatically add `deprecation_date` field to buildpack dependencies if requested
  carton/buildpack_dependency.go
  cmd/update-buildpack-dependency/main.go
  go.mod
  go.sum
  internal/eol.go
  internal/eol_test.go
  internal/init_test.go
Labels: type:enhancement, semver:minor

#356 Bump v2 go.mod versions
  .github/pipeline-version
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
  .gitignore
  dependency_cache.go
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: type:dependency-upgrade, semver:patch
